name: Kimmik
favicon: null
layout_spectrum: 0.816769267199561
typography_spectrum: 0.6193134244531393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.23616832657717168
  lightness: 0.9020941762719303
  saturation: 0.8941128891892731
  rhythmicContrast: 0.4184454244095832
purpose: []
